### ISSUE TITLE
Reduce Repetition of Properties

### ISSUE THREAD

**Issue by cyouh95** [nervermore2/prj-rev-bwfs-dasmoto#3]
You could specify the shared properties among the 3 `h2` headings by using `h2` as the selector. That way, all that's left to specify for each individual one is its `background-color`.

```css
h2 {
  font-family:Helvetica;
  font-size:32px;
  font-weight:bold;
  color:white;
}
```

https://github.com/nervermore2/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L10-L31
